// apps/web/src/pages/JobPage.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import {
  Button,
  Card,
  Col,
  Progress,
  Row,
  Space,
  Table,
  Tag,
  Typography,
  Upload,
  message,
  Descriptions,
} from 'antd'
import type { ColumnsType } from 'antd/es/table'
import type { UploadFile } from 'antd/es/upload/interface'
import {
  fetchCandidates,
  fetchJob,
  fetchMatches,
  triggerMatch,
  uploadResumes,
  type Candidate,
  type Job,
  type MatchReport,
} from '../api'

export function JobPage() {
  const { jobId } = useParams()
  const id = Number(jobId)
  const navigate = useNavigate()
  const [job, setJob] = useState<Job | null>(null)
  const [candidates, setCandidates] = useState<Candidate[]>([])
  const [matches, setMatches] = useState<MatchReport[]>([])
  const [uploading, setUploading] = useState(false)
  const [matching, setMatching] = useState(false)
  const uploadingLock = useRef(false)

  const reload = useCallback(async () => {
    if (!id) return
    const [j, c, m] = await Promise.all([fetchJob(id), fetchCandidates(id), fetchMatches(id)])
    setJob(j)
    setCandidates(c)
    setMatches(m)
  }, [id])

  useEffect(() => {
    reload().catch(() => message.error('加载岗位失败'))
  }, [reload])

  const onUploadFiles = async (files: File[]) => {
    if (!files.length || uploadingLock.current) return
    uploadingLock.current = true
    setUploading(true)
    try {
      await uploadResumes(id, files)
      await reload()
      message.success(`已上传并解析 ${files.length} 份简历`)
    } catch (e: unknown) {
      const err = e as { response?: { data?: { error?: string } }; message?: string }
      message.error(err.response?.data?.error || err.message || '上传失败')
    } finally {
      uploadingLock.current = false
      setUploading(false)
    }
  }

  const onMatch = async () => {
    setMatching(true)
    try {
      await triggerMatch(id)
      await reload()
      message.success('匹配完成')
    } catch (e: unknown) {
      const err = e as { response?: { data?: { error?: string } } }
      message.error(err.response?.data?.error || '匹配失败')
    } finally {
      setMatching(false)
    }
  }

  const columns: ColumnsType<MatchReport> = [
    {
      title: '排名',
      width: 70,
      render: (_, __, index) => index + 1,
    },
    {
      title: '候选人',
      dataIndex: 'candidateName',
      render: (v, row) => v || row.fileName,
    },
    {
      title: '门槛',
      dataIndex: 'passHardGate',
      width: 100,
      render: (v: boolean) => (v ? <Tag color="success">通过</Tag> : <Tag color="warning">未过</Tag>),
    },
    {
      title: '综合分',
      dataIndex: 'totalScore',
      width: 100,
      render: (v?: number) => <span className="score">{v?.toFixed(1) ?? '-'}</span>,
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 90,
    },
    {
      title: '摘要',
      dataIndex: 'summary',
      ellipsis: true,
    },
    {
      title: '操作',
      width: 100,
      render: (_, row) => (
        <Button type="link" onClick={() => navigate(`/candidates/${row.candidateId}`)}>
          详情
        </Button>
      ),
    },
  ]

  if (!job) return null

  return (
    <Space direction="vertical" size={16} style={{ width: '100%' }}>
      <Typography.Text>
        <Link to="/">← 返回</Link>
      </Typography.Text>

      <Card title={job.title}>
        <Typography.Paragraph type="secondary">{job.jdText}</Typography.Paragraph>
        <Descriptions size="small" column={1} title="硬性门槛">
          {job.hardRequirements?.map((h) => (
            <Descriptions.Item key={h.key} label={h.label}>
              {h.operator} {h.value}
            </Descriptions.Item>
          ))}
        </Descriptions>
        <Typography.Text strong>能力权重</Typography.Text>
        <Row gutter={[12, 12]} style={{ marginTop: 8 }}>
          {job.dimensions?.map((d) => (
            <Col span={12} key={d.name}>
              <div className="panel">
                <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                  <span>{d.name}</span>
                  <span>{Math.round(d.weight * 100)}%</span>
                </div>
                <Progress percent={Math.round(d.weight * 100)} showInfo={false} strokeColor="#1f4b7a" />
              </div>
            </Col>
          ))}
        </Row>
      </Card>

      <Card
        title="简历"
        extra={
          <Space>
            <Upload
              multiple
              accept=".pdf,.docx,.txt,.md"
              showUploadList={false}
              fileList={[] as UploadFile[]}
              beforeUpload={(file, fileList) => {
                // 只在本批最后一份时触发，避免 onChange 累积重复上传
                if (file === fileList[fileList.length - 1]) {
                  void onUploadFiles(fileList)
                }
                return false
              }}
            >
              <Button loading={uploading} disabled={matching}>
                上传简历
              </Button>
            </Upload>
            <Button type="primary" loading={matching} disabled={uploading} onClick={onMatch}>
              重新匹配
            </Button>
          </Space>
        }
      >
        <Table
          size="small"
          rowKey="id"
          pagination={false}
          dataSource={candidates}
          columns={[
            { title: '文件', dataIndex: 'fileName' },
            {
              title: '姓名',
              render: (_, r) => r.profile?.name || '-',
            },
            {
              title: '解析',
              dataIndex: 'parseStatus',
              render: (v: string) => <Tag>{v}</Tag>,
            },
            {
              title: '年限',
              render: (_, r) => r.profile?.yearsOfExperience ?? '-',
            },
          ]}
        />
      </Card>

      <Card title="可解释匹配结果榜">
        <Table rowKey="id" size="middle" columns={columns} dataSource={matches} pagination={false} />
      </Card>
    </Space>
  )
}

// apps/web/src/pages/JobPage.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, type UploadRawFile } from 'element-plus'
import {
  fetchCandidates,
  fetchJob,
  fetchMatches,
  triggerMatch,
  uploadResumes,
  type Candidate,
  type Job,
  type MatchReport,
} from '../api'

const route = useRoute()
const router = useRouter()
const id = computed(() => Number(route.params.jobId))

const job = ref<Job | null>(null)
const candidates = ref<Candidate[]>([])
const matches = ref<MatchReport[]>([])
const uploading = ref(false)
const matching = ref(false)
let uploadingLock = false
let pendingUploadFiles: File[] = []
let uploadFlushTimer: ReturnType<typeof setTimeout> | null = null

async function reload() {
  if (!id.value) return
  const [j, c, m] = await Promise.all([
    fetchJob(id.value),
    fetchCandidates(id.value),
    fetchMatches(id.value),
  ])
  job.value = j
  candidates.value = c
  matches.value = m
}

onMounted(() => {
  reload().catch(() => ElMessage.error('加载岗位失败'))
})

async function onUploadFiles(files: File[]) {
  if (!files.length || uploadingLock) return
  uploadingLock = true
  uploading.value = true
  try {
    await uploadResumes(id.value, files)
    await reload()
    ElMessage.success(`已上传并解析 ${files.length} 份简历`)
  } catch (e: unknown) {
    const err = e as { response?: { data?: { error?: string } }; message?: string }
    ElMessage.error(err.response?.data?.error || err.message || '上传失败')
  } finally {
    uploadingLock = false
    uploading.value = false
  }
}

function beforeUpload(file: UploadRawFile) {
  pendingUploadFiles.push(file)
  if (uploadFlushTimer) clearTimeout(uploadFlushTimer)
  uploadFlushTimer = setTimeout(() => {
    const batch = [...pendingUploadFiles]
    pendingUploadFiles = []
    uploadFlushTimer = null
    void onUploadFiles(batch)
  }, 0)
  return false
}

async function onMatch() {
  matching.value = true
  try {
    await triggerMatch(id.value)
    await reload()
    ElMessage.success('匹配完成')
  } catch (e: unknown) {
    const err = e as { response?: { data?: { error?: string } } }
    ElMessage.error(err.response?.data?.error || '匹配失败')
  } finally {
    matching.value = false
  }
}
</script>

<template>
  <div v-if="job" class="page-stack">
    <RouterLink class="back-link" to="/">← 返回</RouterLink>

    <el-card shadow="never" :header="job.title">
      <p class="jd-text">{{ job.jdText }}</p>

      <h4 class="block-title">硬性门槛</h4>
      <el-descriptions :column="1" size="small" border>
        <el-descriptions-item v-for="h in job.hardRequirements" :key="h.key" :label="h.label">
          {{ h.operator }} {{ h.value }}
        </el-descriptions-item>
      </el-descriptions>

      <h4 class="block-title">能力权重</h4>
      <el-row :gutter="12">
        <el-col v-for="d in job.dimensions" :key="d.name" :span="12" class="dim-col">
          <div class="panel">
            <div class="dim-row">
              <span>{{ d.name }}</span>
              <span>{{ Math.round(d.weight * 100) }}%</span>
            </div>
            <el-progress
              :percentage="Math.round(d.weight * 100)"
              :show-text="false"
              color="#1f4b7a"
            />
          </div>
        </el-col>
      </el-row>
    </el-card>

    <el-card shadow="never">
      <template #header>
        <div class="card-header">
          <span>简历</span>
          <el-space>
            <el-upload
              multiple
              accept=".pdf,.docx,.txt,.md"
              :show-file-list="false"
              :before-upload="beforeUpload"
            >
              <el-button :loading="uploading" :disabled="matching">上传简历</el-button>
            </el-upload>
            <el-button type="primary" :loading="matching" :disabled="uploading" @click="onMatch">
              重新匹配
            </el-button>
          </el-space>
        </div>
      </template>

      <el-table :data="candidates" size="small" row-key="id">
        <el-table-column prop="fileName" label="文件" />
        <el-table-column label="姓名">
          <template #default="{ row }">{{ row.profile?.name || '-' }}</template>
        </el-table-column>
        <el-table-column prop="parseStatus" label="解析" width="100">
          <template #default="{ row }">
            <el-tag size="small">{{ row.parseStatus }}</el-tag>
          </template>
        </el-table-column>
        <el-table-column label="年限" width="90">
          <template #default="{ row }">{{ row.profile?.yearsOfExperience ?? '-' }}</template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-card shadow="never" header="可解释匹配结果榜">
      <el-table :data="matches" row-key="id">
        <el-table-column label="排名" width="70">
          <template #default="{ $index }">{{ $index + 1 }}</template>
        </el-table-column>
        <el-table-column label="候选人">
          <template #default="{ row }">{{ row.candidateName || row.fileName }}</template>
        </el-table-column>
        <el-table-column label="门槛" width="100">
          <template #default="{ row }">
            <el-tag :type="row.passHardGate ? 'success' : 'warning'" size="small">
              {{ row.passHardGate ? '通过' : '未过' }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="综合分" width="100">
          <template #default="{ row }">
            <span class="score">{{ row.totalScore?.toFixed(1) ?? '-' }}</span>
          </template>
        </el-table-column>
        <el-table-column prop="status" label="状态" width="90" />
        <el-table-column prop="summary" label="摘要" show-overflow-tooltip />
        <el-table-column label="操作" width="100">
          <template #default="{ row }">
            <el-button type="primary" link @click="router.push(`/candidates/${row.candidateId}`)">
              详情
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>
  </div>
</template>

<style scoped>
.page-stack {
  display: flex;
  flex-direction: column;
  gap: 16px;
  width: 100%;
}

.back-link {
  color: #1f4b7a;
  text-decoration: none;
  font-size: 14px;
}

.jd-text {
  margin: 0 0 12px;
  color: #5b6b7c;
  line-height: 1.6;
}

.block-title {
  margin: 16px 0 8px;
  font-size: 14px;
  font-weight: 600;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.dim-col {
  margin-bottom: 12px;
}

.dim-row {
  display: flex;
  justify-content: space-between;
  margin-bottom: 6px;
}
</style>
